# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Infrastructure\FakerPHP\Factory\FakerServiceFactory: ~    
    Application\Factory\Extractor\PersonExtractorFactory: ~    
    Application\Factory\Service\Person\PersonServiceFactory: ~    

    Infrastructure\FakerPHP\Service\FakerService:        
        factory: '@Infrastructure\FakerPHP\Factory\FakerServiceFactory'   
        autowire: false 
    
    Application\Service\FakeData\GenerateFakeDataServiceInterface: '@Infrastructure\FakerPHP\Service\FakerService'

    application.extractor.person:
        class: Application\Extractor\PersonExtractor 
        factory: '@Application\Factory\Extractor\PersonExtractorFactory'
        autowire: false
        
    application.service.person.person:
        class: Application\Service\Person\PersonService
        factory: '@Application\Factory\Service\Person\PersonServiceFactory'
        autowire: false
        arguments:
            - '@Application\Service\FakeData\GenerateFakeDataServiceInterface'
               
    Infrastructure\Symfony\Controller\PersonController:        
        class: Infrastructure\Symfony\Controller\PersonController    
        autowire: false
        tags: ['controller.service_arguments']
        arguments:
            - '@application.service.person.person'
            - '@application.extractor.person'